version: '3'

services:
  spark-master:
    image: bitnami/spark:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
    networks:
      - spark-network

  spark-worker-1:
    image: bitnami/spark:latest
    deploy:
      replicas: 1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - spark-network

  spark-worker-2:
    image: bitnami/spark:latest
    deploy:
      replicas: 1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - spark-network
    
   
  mongodb-1:
    image: bitnami/mongodb:latest
    deploy:
      replicas: 1
    ports:
      - "27017:27017"
    volumes:
      - mongodb-volume1:/var/lib/mongodb
    networks:
      - spark-network

  mongodb-2:
    image: bitnami/mongodb:latest
    deploy:
      replicas: 1
    ports:
      - "27018:27017"
    volumes:
      - mongodb-volume2:/var/lib/mongodb
    networks:
      - spark-network

networks:
  spark-network:
    driver: overlay

volumes:
  mongodb-volume1:
    driver: local
  mongodb-volume2:
    driver: local
