version: '3'

services:
  spark-master:
    image: bitnami/spark:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
    networks:
      - spark-network

  spark-worker-1:
    image: bitnami/spark:latest
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - spark-network

  # spark-worker-2:
  #   image: bitnami/spark:latest
  #   deploy:
  #     replicas: 1
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark-master:7077
  #   networks:
  #     - spark-network

  jupyterlab:
    image: jupyter-image:latest
    ports:
      - "8888:8888"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - spark-network

networks:
  spark-network:
    driver: overlay
